### ISSUE TITLE
FileNotFoundError on pascal3d+

### ISSUE THREAD

**Issue by dssrgu** [senthilps8/demystifyssl#2]
Hi,

When trying to experiment on the pascal3d+ dataset with ```python extract_features/pascal3d/extract_pascal3d_features.py dataset=pascal3d model.load_path=$MODELPATH hparams.exp_name=$MODELNAME```,

I get this error:

```
Traceback (most recent call last):
  File "extract_features/pascal3d/extract_pascal3d_features.py", line 77, in main
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/home/dssrgu/demystifyssl/data/pascal3d/Image_sets/aeroplane_pascal.txt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

It seems the ```pascal3d/Image_sets``` directory does not contain any files named *_.pascal.txt.

Does the dataset require some sort of preprocessing?

The data was prepared using the following script from the README:

```
mkdir data
cd data
wget ftp://cs.stanford.edu/cs/cvgl/PASCAL3D+_release1.1.zip
unzip PASCAL3D+_release1.1.zip
mv PASCAL3D+_release1.1 pascal3d
```

**Comment by senthilps8** [comment]
I don't recall doing anything with the ImageSets, but you can replicate the contents of my `ImageSets/` folder from this tarball:
https://cs.cmu.edu/~spurushw/publication/demystifyssl/imagesets.tar.gz

**Comment by pietroastolfi** [comment]
Hi, I m getting the same error and the archive you have shared is no more available.

> I don't recall doing anything with the ImageSets

You are using it in this [codeblock](https://github.com/senthilps8/demystifyssl/blob/407f2942d82862e11bd7ac8253d6ee077aca60ae/extract_features/pascal3d/extract_pascal3d_features.py#L70-L90)

Thanks,

Pietro

**Comment by senthilps8** [comment]
The link should work now. It was accidentally deleted.
